### ISSUE TITLE
Incompatible with mobie update site

### ISSUE THREAD

**Issue by K-Meech** [K-Meech/crosshair#5]
The current imagej-utils jar I ship is incompatible with mobie.

Opening mobie (with platybrowser datasets) with both enabled leads to the error:

```
java.lang.NoSuchMethodError: de.embl.cba.bdv.utils.BdvUtils.getViewerFrame(Lbdv/util/BdvHandle;)Lbdv/viewer/ViewerFrame;
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:372)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:338)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:295)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:46)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:32)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:99)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:59)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:19)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by K-Meech** [comment]
@tischi - any idea why this happens? Has something changed between the latest snapshot & the version you ship with mobie?

**Comment by tischi** [comment]
@K-Meech 
...very likely the issue likely is that the `imagej-utils` that I ship with MoBIE is quite old. 
The problem is that I could not deploy the very latest version of MoBIE due to this issue:
https://github.com/fiji/fiji/issues/263
I hope this gets resolved very soon!

**Comment by K-Meech** [comment]
The update sites are compatible now
